import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─── Brand Colors ────────────────────────────────────────────────────────────
const C = {
  primary:  [74, 43, 142],
  success:  [16, 185, 129],
  warning:  [245, 158, 11],
  error:    [239, 68, 68],
  muted:    [120, 120, 140],
  dark:     [20, 20, 35],
  light:    [248, 248, 255],
  border:   [220, 220, 235],
};

// ─── Helpers ─────────────────────────────────────────────────────────────────
const sentimentColor = (label) => {
  if (label === 'Positive') return C.success;
  if (label === 'Negative') return C.error;
  return C.warning;
};

const scoreColor = (pct) => {
  if (pct >= 75) return C.success;
  if (pct >= 50) return C.warning;
  return C.error;
};

const drawHeader = (doc, title, subtitle) => {
  // Purple header bar
  doc.setFillColor(...C.primary);
  doc.rect(0, 0, 210, 32, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('FeedbackPulse', 14, 14);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 185, 255);
  doc.text(title, 14, 22);
  if (subtitle) {
    doc.setTextColor(200, 200, 220);
    doc.text(subtitle, 14, 29);
  }

  // Date stamp top-right
  doc.setFontSize(8);
  doc.setTextColor(200, 185, 255);
  doc.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), 196, 14, { align: 'right' });

  return 44; // yPos after header
};

const drawSectionTitle = (doc, text, yPos) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...C.primary);
  doc.text(text, 14, yPos);
  doc.setDrawColor(...C.primary);
  doc.setLineWidth(0.4);
  doc.line(14, yPos + 2, 196, yPos + 2);
  return yPos + 10;
};

const drawStatCard = (doc, x, y, w, label, value, color) => {
  doc.setFillColor(...C.light);
  doc.setDrawColor(...C.border);
  doc.roundedRect(x, y, w, 18, 3, 3, 'FD');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text(label.toUpperCase(), x + w / 2, y + 7, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...color);
  doc.text(String(value), x + w / 2, y + 14, { align: 'center' });
};

const checkPage = (doc, yPos, needed = 30) => {
  if (yPos + needed > 275) {
    doc.addPage();
    return 20;
  }
  return yPos;
};

// ─── FULL DEPARTMENT REPORT ──────────────────────────────────────────────────
export const generatePDFReport = (profile, insights, feedbackList, subjects = [], staff = []) => {
  try {
    const doc = new jsPDF();

    let y = drawHeader(
      doc,
      `Department Report — ${profile?.department || 'N/A'} | Year ${profile?.year || '?'}`,
      `Generated by ${profile?.full_name || 'CR'} on ${new Date().toLocaleDateString()}`
    );

    // ── Overall Stats Row ──
    const total = feedbackList?.length || 0;
    const pos   = feedbackList?.filter(f => f.sentiment_label === 'Positive').length || 0;
    const neu   = feedbackList?.filter(f => f.sentiment_label === 'Neutral').length || 0;
    const neg   = feedbackList?.filter(f => f.sentiment_label === 'Negative').length || 0;
    const sat   = insights?.satisfaction_score || (total > 0 ? Math.round((pos / total) * 100) : 0);

    const cardW = 42;
    const gap   = 3;
    const startX = 14;
    drawStatCard(doc, startX,              y, cardW, 'Total Feedback', total, C.primary);
    drawStatCard(doc, startX + cardW + gap,  y, cardW, 'Positive',       pos,   C.success);
    drawStatCard(doc, startX + (cardW+gap)*2, y, cardW, 'Neutral',        neu,   C.warning);
    drawStatCard(doc, startX + (cardW+gap)*3, y, cardW, 'Negative',       neg,   C.error);
    drawStatCard(doc, startX + (cardW+gap)*4, y, cardW, 'Satisfaction',   `${sat}%`, sat >= 70 ? C.success : sat >= 40 ? C.warning : C.error);
    y += 26;

    // ── AI Insights ──
    if (insights) {
      y = drawSectionTitle(doc, 'AI Intelligence Summary', y);

      const drawBullets = (title, items, color, icon) => {
        if (!items?.length) return;
        y = checkPage(doc, y, 20);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...color);
        doc.text(`${icon}  ${title}`, 14, y);
        y += 6;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(50, 50, 70);
        items.forEach(item => {
          y = checkPage(doc, y, 8);
          const lines = doc.splitTextToSize(`• ${item}`, 176);
          doc.text(lines, 20, y);
          y += lines.length * 5 + 1;
        });
        y += 4;
      };

      if (insights.ai_summary) {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.setTextColor(...C.muted);
        const lines = doc.splitTextToSize(insights.ai_summary, 180);
        doc.text(lines, 14, y);
        y += lines.length * 5 + 6;
      }

      drawBullets('Key Strengths',         insights.ai_strengths,     C.success, '+');
      drawBullets('Critical Issues',        insights.ai_improvements,  C.error,   '!');
      drawBullets('Recommended Actions',    insights.ai_suggestions,   C.primary, '>');
    }

    // ── Subject-Wise Summary Table ──
    y = checkPage(doc, y, 40);
    y = drawSectionTitle(doc, 'Subject-Wise Performance Summary', y);

    const subjectRows = subjects.map(sub => {
      const fb    = feedbackList?.filter(f => f.subject_id === sub.id) || [];
      const sPos  = fb.filter(f => f.sentiment_label === 'Positive').length;
      const sNeg  = fb.filter(f => f.sentiment_label === 'Negative').length;
      const sNeu  = fb.filter(f => f.sentiment_label === 'Neutral').length;
      const sPct  = fb.length > 0 ? Math.round((sPos / fb.length) * 100) : 0;
      const staffObj = staff.find(s => s.subject_id === sub.id);
      return [sub.name, staffObj?.name || '—', fb.length, sPos, sNeu, sNeg, `${sPct}%`];
    });

    autoTable(doc, {
      startY: y,
      head: [['Subject', 'Staff', 'Total', 'Positive', 'Neutral', 'Negative', 'Score']],
      body: subjectRows,
      theme: 'grid',
      headStyles: { fillColor: C.primary, textColor: 255, fontStyle: 'bold', fontSize: 9 },
      styles: { fontSize: 8.5, cellPadding: 3, font: 'helvetica' },
      columnStyles: {
        0: { cellWidth: 45 },
        1: { cellWidth: 38 },
        2: { cellWidth: 18, halign: 'center' },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 20, halign: 'center' },
        5: { cellWidth: 20, halign: 'center' },
        6: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
      },
      didParseCell(data) {
        if (data.section === 'body') {
          if (data.column.index === 3) data.cell.styles.textColor = C.success;
          if (data.column.index === 5) data.cell.styles.textColor = C.error;
          if (data.column.index === 4) data.cell.styles.textColor = C.warning;
          if (data.column.index === 6) {
            const pct = parseInt(data.cell.raw);
            data.cell.styles.textColor = scoreColor(pct);
          }
        }
      }
    });
    y = doc.lastAutoTable.finalY + 14;

    // ── Per-Subject Detailed Feedback ──
    subjects.forEach(sub => {
      const subFb = feedbackList?.filter(f => f.subject_id === sub.id) || [];
      if (subFb.length === 0) return;

      doc.addPage();
      y = drawHeader(
        doc,
        `Subject Report — ${sub.name}`,
        `${profile?.department || ''} | Year ${profile?.year || ''}`
      );

      const sPos = subFb.filter(f => f.sentiment_label === 'Positive').length;
      const sNeg = subFb.filter(f => f.sentiment_label === 'Negative').length;
      const sNeu = subFb.filter(f => f.sentiment_label === 'Neutral').length;
      const sPct = subFb.length > 0 ? Math.round((sPos / subFb.length) * 100) : 0;
      const staffObj = staff.find(s => s.subject_id === sub.id);

      // Mini stat row
      const cw = 44;
      drawStatCard(doc, 14,           y, cw, 'Total',    subFb.length,   C.primary);
      drawStatCard(doc, 14 + cw + 3,  y, cw, 'Positive', sPos,           C.success);
      drawStatCard(doc, 14 + (cw+3)*2, y, cw, 'Neutral', sNeu,           C.warning);
      drawStatCard(doc, 14 + (cw+3)*3, y, cw, 'Score',   `${sPct}%`,     scoreColor(sPct));
      y += 26;

      if (staffObj) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...C.muted);
        doc.text(`Staff: ${staffObj.name}`, 14, y);
        y += 10;
      }

      y = drawSectionTitle(doc, 'Individual Feedback Entries', y);

      const rows = subFb.map(f => [
        new Date(f.created_at).toLocaleDateString(),
        f.sentiment_label || 'Neutral',
        f.feedback_text || '—'
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Date', 'Sentiment', 'Feedback Details']],
        body: rows,
        theme: 'striped',
        headStyles: { fillColor: C.primary, textColor: 255, fontStyle: 'bold', fontSize: 9 },
        styles: { fontSize: 8.5, cellPadding: 3, font: 'helvetica', overflow: 'linebreak' },
        columnStyles: {
          0: { cellWidth: 24 },
          1: { cellWidth: 24, fontStyle: 'bold', halign: 'center' },
          2: { cellWidth: 'auto' },
        },
        didParseCell(data) {
          if (data.section === 'body' && data.column.index === 1) {
            data.cell.styles.textColor = sentimentColor(data.cell.raw);
          }
        }
      });
    });

    // ── Footer on every page ──
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...C.muted);
      doc.text(`FeedbackPulse — Confidential | Page ${i} of ${pageCount}`, 105, 292, { align: 'center' });
    }

    doc.save(`FeedbackPulse_Full_Report_${profile?.department || 'Dept'}_${Date.now()}.pdf`);
  } catch (err) {
    console.error('PDF generation error:', err);
    alert('Failed to generate PDF. Please try again.');
  }
};

// ─── SINGLE SUBJECT REPORT ────────────────────────────────────────────────────
export const generateSubjectPDF = (subject, feedbackList, profile, staffObj) => {
  try {
    const doc = new jsPDF();

    let y = drawHeader(
      doc,
      `Subject Report — ${subject.name}`,
      `${profile?.department || ''} | Year ${profile?.year || ''} | Generated ${new Date().toLocaleDateString()}`
    );

    const pos = feedbackList.filter(f => f.sentiment_label === 'Positive').length;
    const neg = feedbackList.filter(f => f.sentiment_label === 'Negative').length;
    const neu = feedbackList.filter(f => f.sentiment_label === 'Neutral').length;
    const pct = feedbackList.length > 0 ? Math.round((pos / feedbackList.length) * 100) : 0;

    // Stat cards
    const cw = 44;
    drawStatCard(doc, 14,            y, cw, 'Total Responses', feedbackList.length, C.primary);
    drawStatCard(doc, 14 + cw + 3,   y, cw, 'Positive',        pos,                 C.success);
    drawStatCard(doc, 14 + (cw+3)*2, y, cw, 'Negative',        neg,                 C.error);
    drawStatCard(doc, 14 + (cw+3)*3, y, cw, 'Satisfaction',    `${pct}%`,           scoreColor(pct));
    y += 26;

    if (staffObj) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(...C.muted);
      doc.text(`Assigned Staff: ${staffObj.name}`, 14, y);
      y += 10;
    }

    // Neutral count note
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C.muted);
    doc.text(`Neutral responses: ${neu}`, 14, y);
    y += 10;

    y = drawSectionTitle(doc, 'Individual Feedback Entries', y);

    if (feedbackList.length === 0) {
      doc.setFontSize(10);
      doc.setTextColor(...C.muted);
      doc.text('No feedback submitted for this subject yet.', 14, y);
    } else {
      const rows = feedbackList.map(f => [
        new Date(f.created_at).toLocaleDateString(),
        f.sentiment_label || 'Neutral',
        f.feedback_text || '—'
      ]);

      autoTable(doc, {
        startY: y,
        head: [['Date', 'Sentiment', 'Feedback Details']],
        body: rows,
        theme: 'striped',
        headStyles: { fillColor: C.primary, textColor: 255, fontStyle: 'bold', fontSize: 9 },
        styles: { fontSize: 8.5, cellPadding: 3.5, font: 'helvetica', overflow: 'linebreak' },
        columnStyles: {
          0: { cellWidth: 26 },
          1: { cellWidth: 26, fontStyle: 'bold', halign: 'center' },
          2: { cellWidth: 'auto' },
        },
        didParseCell(data) {
          if (data.section === 'body' && data.column.index === 1) {
            data.cell.styles.textColor = sentimentColor(data.cell.raw);
          }
        }
      });
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...C.muted);
      doc.text(`FeedbackPulse — Confidential | Page ${i} of ${pageCount}`, 105, 292, { align: 'center' });
    }

    const safeName = subject.name.replace(/[^a-z0-9]/gi, '_');
    doc.save(`FeedbackPulse_${safeName}_${profile?.department || 'Dept'}_${Date.now()}.pdf`);
  } catch (err) {
    console.error('Subject PDF error:', err);
    alert('Failed to generate subject PDF. Please try again.');
  }
};
